controller_manager:
  ros__parameters:
    update_rate: 100 # 100hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controller:
      type: position_controllers/JointGroupPositionController

position_controller:
  ros__parameters:
    joints:
      - theta1
      - theta2
      - d3
      - theta4